#server:
#  port: 8081

#spring:
  #application:
    #name: cliente-service

  #r2dbc:
    #url: r2dbc:postgresql://localhost:5432/arka_clientes
    #username: arka
    #password: arka
    #pool:
      #enabled: true

  # Logs y trazas mínimas
  #main:
    #web-application-type: reactive

#logging:
  #level:
    #org.springframework.r2dbc: INFO
    #org.springframework.web: INFO
